version: "3.9"

services:
  mongo:
    image: mongo:8
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  api:
    build: ./api
    command: pnpm dev
    volumes:
      - ./api:/app
    ports:
      - "3000:3000"
    env_file:
      - ./api/.env
    depends_on:
      - mongo
      - redis

  worker:
    build: ./worker
    command: pnpm dev
    volumes:
      - ./worker:/app
    env_file:
      - ./worker/.env
    depends_on:
      - api

  sink:
    build: ./sink
    command: pnpm dev
    volumes:
      - ./sink:/app
    ports:
      - "4000:4000"
    env_file:
      - ./sink/.env
    depends_on:
      - worker

volumes:
  mongo_data:

