version: "0.1"

services:
  mongo:
    image: mongo:8
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  api:
    build: ./api
    command: pnpm dev
    volumes:
      - ./api:/app
    ports:
      - "3000:3000"
    env_file:
      - ./api/.env

  worker:
    build: ./worker
    command: pnpm dev
    volumes:
      - ./worker:/app
    env_file:
      - ./worker/.env

  sink:
    build: ./sink
    command: pnpm dev
    volumes:
      - ./sink:/app
    ports:
      - "4000:4000"
    env_file:
      - ./sink/.env

volumes:
  mongo_data:

