version: "3.9"

services:
  mongo:
    image: mongo:8
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    command: pnpm dev
    volumes:
      - ./api:/app
    ports:
      - "3000:3000"
    env_file:
      - ./api/.env
    depends_on:
      - mongo
      - redis

  worker:
    build: ./worker
    command: pnpm dev
    volumes:
      - ./worker:/app
    env_file:
      - ./worker/.env
    depends_on:
      - api

  sink:
    build: ./sink
    command: pnpm dev
    volumes:
      - ./sink:/app
    ports:
      - "4000:4000"
    env_file:
      - ./sink/.env
    depends_on:
      - worker

volumes:
  mongo_data:

